package com.ztt.domain;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.nickname
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.createTime
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.nickname
     *
     * @return the value of orders.nickname
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.nickname
     *
     * @param nickname the value for orders.nickname
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.createTime
     *
     * @return the value of orders.createTime
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.createTime
     *
     * @param createtime the value for orders.createTime
     *
     * @mbggenerated Wed May 23 09:11:03 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}