eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
      lease-expiration-duration-in-seconds: 2
      lease-renewal-interval-in-seconds:  1
      instance-id: web-1

spring:
  profiles:
    active: prod
  jackson: #序列化时间格式化 Srping boot默认使用Jackson来进行序列化和返序列化
    date-format: yyyy年MM月dd日 HH:mm:ss
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        connectionTimeout: 10000 # 定义获取连接的超时时间。最小250ms,默认30s
        idleTimeout: 50000 # 定义连接空闲时间。最小10s,默认10m
        maximumPoolSize: 100 # 定义最大的连接数。默认10
        connectionTestQuery: select 1 # 从连接池获取到连接后，进行检查的查询语句。推荐设置该属性。默认值为none
        maxLifeTime: 600000 # 定义连接的最大生命周期。推荐设置该属性。最小30s，默认30m
  application:
    name: springboot-ztt
  devtools:
    restart:
      additional-paths:
        - C:\Users\zhangtt\IdeaProjects\springboot2.1.0\restart
      enabled: false

server:
  servlet:
    context-path: /springboot2

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ztt.domain


#logging:
 # level:
  #  com.ztt.controller.UserController: 'off'   #路径下日志不会被打印


--- #yml支持多文档块的方式
spring:
  profiles: dev

server:
  port: 8080

manSize: 176
manAge: 24
content: "年龄${manAge},身高${manSize}"

user:
  id: 100
  name: ???
  nickname: zhangtietuo-dev
---
spring:
  profiles: test
server:
  port: 8082
---
spring:
  profiles: prod

server:
  port: 8081
  servlet:
    context-path: /myProject #配置项目根目录 springboot2不好用？

manSize: 176
manAge: 24
content: "年龄${manAge},身高${manSize}"

user:
  id: ${random.int[20,30]} #项目启动后就不会再改变
  name: ???!
  nickname: zhangtietuo-prod

my:
  property:
    name: zhangtietuo
    age: 25
    #- abc
    #- def
    #'[foo.baz]': bar



